version: '3.8'

services:
  todo_container:
    build: .
    container_name: todo_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
